import { test, expect, type Page } from '@playwright/test';
import {
  gotoPage,
  openTable,
  getColumnSeparatorPosition,
  dragColumnSeparator,
  markerAtCoordinates,
} from './utils';

async function waitForLoadingDone(page: Page) {
  await expect(
    page.locator('.iris-grid .iris-grid-loading-status')
  ).toHaveCount(0);
}

test('can open a simple table', async ({ page }) => {
  await gotoPage(page, '');
  await openTable(page, 'simple_table');
  // Now we should be able to check the snapshot
  await expect(page.locator('.iris-grid-panel .iris-grid')).toHaveScreenshot();
});

test('can make a non-contiguous table row selection', async ({ page }) => {
  await gotoPage(page, '');
  await openTable(page, 'simple_table');

  const grid = await page.locator('.iris-grid-panel .iris-grid');
  const gridLocation = await grid.boundingBox();
  expect(gridLocation).not.toBeNull();
  if (gridLocation === null) return;

  // Based on default row and header height in IrisGridTheme
  // Ideally this would be calculated from the current theme
  const rowHeight = 19;
  const columnHeaderHeight = 30;

  // ctrl+click on every other row for 9 rows, starting at row 0 after the header
  /* eslint-disable no-await-in-loop */
  for (let i = 0; i < 9; i += 1) {
    await page.keyboard.down('Control');
    await page.mouse.click(
      gridLocation.x + 1, // plus one so we click on the first pixel not 0
      gridLocation.y + 1 + columnHeaderHeight + rowHeight * i * 2
      // times 2 because we're skipping every other row
    );
    await page.keyboard.up('Control');
  }
  /* eslint-enable no-await-in-loop */

  await expect(page.locator('.iris-grid-panel .iris-grid')).toHaveScreenshot();
});

test('can open a table with column header groups', async ({ page }) => {
  await gotoPage(page, '');
  await openTable(page, 'simple_table_header_group');
  // Now we should be able to check the snapshot
  await expect(page.locator('.iris-grid-panel .iris-grid')).toHaveScreenshot();
});

test('can open a table with column header groups and hidden columns', async ({
  page,
}) => {
  await gotoPage(page, '');
  await openTable(page, 'simple_table_header_group_hide');
  // Now we should be able to check the snapshot
  await expect(page.locator('.iris-grid-panel .iris-grid')).toHaveScreenshot();
});

test.describe('tests simple table operations', () => {
  test.beforeEach(async ({ page }) => {
    await gotoPage(page, '');
    await openTable(page, 'simple_table');
    const tableOperationsMenu = page.locator(
      'data-testid=btn-iris-grid-settings-button-table'
    );
    await tableOperationsMenu.click();

    // Wait for Table Options menu to show
    await expect(page.locator('.table-sidebar')).toHaveCount(1);
  });

  test('can download table successfully', async ({ page, browserName }) => {
    // open Download CSV panel
    await page.locator('data-testid=menu-item-Download CSV').click();

    const downloadButton = page.locator(
      'data-testid=btn-csv-exporter-download'
    );
    expect(downloadButton).toHaveCount(1);

    // try renaming file before downloading
    const fileNameInputField = page.locator(
      'data-testid=input-csv-exporter-file-name'
    );
    // Triple click to highlight current, autogenerated name
    await fileNameInputField.click({ clickCount: 3 });
    await page.keyboard.type('sin-and-cos.csv');
    await expect(fileNameInputField).toHaveValue('sin-and-cos.csv');

    // webkit is flaky
    if (browserName === 'webkit') {
      downloadButton.click();
    } else {
      const downloadPromise = page.waitForEvent('download');
      downloadButton.click();
      await downloadPromise;
    }

    // Wait for download to complete
    await expect(
      page.locator('.progress.progress-bar-striped.progress-bar-animated')
    ).toHaveCount(0);

    await expect(
      page.locator('.progress .progress-bar.bg-success')
    ).toHaveCount(1);
  });

  test('go to', async ({ page }) => {
    // open with sidepanel button
    await page.locator('data-testid=menu-item-Go to').click();

    const gotoBar = page.locator('.iris-grid-bottom-bar.goto-row');
    const gotoBarInputField = gotoBar.getByPlaceholder('Row number');

    // wait for panel to open
    await expect(gotoBarInputField).toHaveCount(1);

    // test invalid row index
    await gotoBarInputField.click();
    await page.keyboard.type('641');
    await expect(gotoBar.locator('.goto-row-wrapper .text-danger')).toHaveCount(
      1
    );

    // test valid row index (row 64)
    await page.keyboard.press('Backspace');
    await expect(gotoBar.locator('.goto-row-wrapper .text-danger')).toHaveCount(
      0
    );

    // Check snapshot
    await expect(page.locator('.iris-grid-column')).toHaveScreenshot();

    // close with sidepanel button
    await page.locator('data-testid=menu-item-Go to').click();

    await expect(gotoBar).toHaveCount(0);
  });

  test('advanced filters', async ({ page }) => {
    // turn quick filters on
    const quickFiltersItem = page.locator(
      'data-testid=menu-item-Quick Filters'
    );
    await quickFiltersItem.click();

    // wait for toggle to switch to 'on'
    await expect(
      quickFiltersItem.locator('.btn.btn-switch.active')
    ).toHaveCount(1);

    // Enabling quick filters should focus the first column
    // Move to the 2nd column (y column)
    await page.keyboard.press('Tab');
    await page.waitForTimeout(200);

    await page
      .locator('.iris-grid .grid-wrapper button.advanced-filter-button')
      .first() // For some reason we render 2 buttons under each other?
      .click();

    // wait for the panel to open
    await expect(page.locator('.advanced-filter-creator')).toHaveCount(1);

    // Apply filter (greater than 0)
    const selectionMenu = page
      .locator('.advanced-filter-creator')
      .locator('select');
    await selectionMenu.click();
    await selectionMenu.selectOption('greaterThan');
    await page
      .locator('.advanced-filter-creator')
      .getByPlaceholder('Enter value')
      .click();
    await page.keyboard.type('0');

    // wait for filter adding to appear
    const addFilterItem = page.locator(
      '.advanced-filter-creator .add-filter-item'
    );
    await expect(addFilterItem).toHaveCount(1);

    // Apply additional filter (OR equal to 0)
    const selectionMenu2 = selectionMenu.nth(1);
    await addFilterItem.locator('button:has-text("OR")').click();
    await selectionMenu2.click();
    await selectionMenu2.selectOption('eq');
    await page
      .locator('.advanced-filter-creator')
      .getByPlaceholder('Enter value')
      .nth(1)
      .click();
    await page.keyboard.type('0');

    await page
      .locator('.advanced-filter-creator')
      .locator('button:has-text("Done")')
      .click();

    // Wait until it's done loading
    await expect(page.locator('.iris-grid .iris-grid-loading')).toHaveCount(0);

    // Check snapshot
    await expect(page.locator('.iris-grid-column')).toHaveScreenshot();

    // quick filter section (previously its own test)

    // check if quick filters are still on
    await expect(
      page
        .locator('data-testid=menu-item-Quick Filters')
        .locator('.btn.btn-switch.active')
    ).toHaveCount(1);

    // Click the quick filter box (x column)
    // Note: This may click in the wrong place if the browser size is changed
    await page
      .locator('.iris-grid .grid-wrapper')
      .click({ position: { x: 20, y: 35 } });

    // Apply filter (greater 37)
    await page.keyboard.type('>37');

    // Wait until it's done loading
    await waitForLoadingDone(page);

    // Check snapshot
    await expect(page.locator('.iris-grid-column')).toHaveScreenshot();
  });
});

test.describe('column separators', () => {
  test.beforeEach(async ({ page }) => {
    await gotoPage(page, '');
    await openTable(page, 'simple_table');
    await waitForLoadingDone(page);
  });

  test('change color on hover', async ({ page }) => {
    // Get the position of the first column separator
    const separatorPos = await getColumnSeparatorPosition(page, 0);

    // Move mouse to separator position to test basic interaction
    await page.mouse.move(separatorPos.x, separatorPos.y);

    // Wait a bit for any cursor updates
    await page.waitForTimeout(100);

    // Take a screenshot to verify interaction
    await expect(page.locator('.iris-grid-panel .iris-grid')).toHaveScreenshot(
      'column-separator-hover.png'
    );
  });

  test('resize column on mouse drag', async ({ page }) => {
    // Perform drag operation to resize column
    await dragColumnSeparator(page, 0, 50);

    // Verify the drag completed without errors
    // In a real implementation, this would trigger actual column resizing
    await page.waitForTimeout(200);

    // Take screenshot to verify any visual changes
    await expect(page.locator('.iris-grid-panel .iris-grid')).toHaveScreenshot(
      'column-resized-after-drag.png'
    );
  });
});

test.describe('column group separators', () => {
  test.beforeEach(async ({ page }) => {
    await gotoPage(page, '');
    // Open table with column groups for group separator testing
    await openTable(page, 'simple_table_header_group');
  });

  test('change color on hover on level 0', async ({ page }) => {
    // Test hover on the parent of the column "X" (column 0, depth 1)
    const separatorPos = await getColumnSeparatorPosition(page, 0, 1);

    // Move mouse to separator position to test hover interaction
    await page.mouse.move(separatorPos.x, separatorPos.y);
    await markerAtCoordinates(page, separatorPos.x, separatorPos.y);
    await page.waitForTimeout(100);

    // Take a screenshot to verify hover state
    await expect(page.locator('.iris-grid-panel .iris-grid')).toHaveScreenshot(
      'column-group-separator-hover.png'
    );
  });

  test('resize column group on mouse drag', async ({ page }) => {
    // Perform drag operation to resize "All" group (last column = 2, depth = 0)
    await dragColumnSeparator(page, 2, 50, 0);
    await page.waitForTimeout(200);

    // Take screenshot to verify visual changes
    await expect(page.locator('.iris-grid-panel .iris-grid')).toHaveScreenshot(
      'column-group-resized-after-drag.png'
    );
  });

  test('resize nested column groups at depth 1', async ({ page }) => {
    // Perform resize of "YandZ" group (last column = 2, depth = 1)
    await dragColumnSeparator(page, 2, -20, 1);
    await page.waitForTimeout(200);

    // Take screenshot to verify depth 1 resize
    await expect(page.locator('.iris-grid-panel .iris-grid')).toHaveScreenshot(
      'nested-group-separator-depth-1-resized.png'
    );
  });
});
