export const SAVE_WORKSPACE = 'SAVE_WORKSPACE';

export const SET_ACTIVE_TOOL = 'SET_ACTIVE_TOOL';

export const SET_COMMAND_HISTORY_STORAGE = 'SET_COMMAND_HISTORY_STORAGE';

export const SET_DASHBOARD_STORAGE = 'SET_DASHBOARD_STORAGE';

export const SET_FILE_STORAGE = 'SET_FILE_STORAGE';

export const SET_PLUGINS = 'SET_PLUGINS';

export const SET_USER = 'SET_USER';

export const SET_WORKSPACE = 'SET_WORKSPACE';

export const SET_WORKSPACE_STORAGE = 'SET_WORKSPACE_STORAGE';
