export const SAVE_WORKSPACE = 'SAVE_WORKSPACE';

export const SET_ACTIVE_TOOL = 'SET_ACTIVE_TOOL';

export const SET_COMMAND_HISTORY_STORAGE = 'SET_COMMAND_HISTORY_STORAGE';

export const SET_DASHBOARD_STORAGE = 'SET_DASHBOARD_STORAGE';

export const SET_DASHBOARD_COLUMNS = 'SET_DASHBOARD_COLUMNS';

export const SET_DASHBOARD_LINKS = 'SET_DASHBOARD_LINKS';

export const ADD_DASHBOARD_LINKS = 'ADD_DASHBOARD_LINKS';

export const DELETE_DASHBOARD_LINKS = 'DELETE_DASHBOARD_LINKS';

export const SET_DASHBOARD_INPUT_FILTERS = 'SET_DASHBOARD_INPUT_FILTERS';

export const SET_DASHBOARD_ISOLATED_LINKER_PANEL_ID =
  'SET_DASHBOARD_ISOLATED_LINKER_PANEL_ID';

export const SET_DASHBOARD_CLOSED_PANELS = 'SET_DASHBOARD_CLOSED_PANELS';

export const SET_DASHBOARD_OPENED_PANEL_MAP = 'SET_DASHBOARD_OPENED_PANEL_MAP';

export const SET_DASHBOARD_PANEL_TABLE_MAP = 'SET_DASHBOARD_PANEL_TABLE_MAP';

export const SET_DASHBOARD_COLUMN_SELECTION_VALIDATOR =
  'SET_DASHBOARD_COLUMN_SELECTION_VALIDATOR';

export const SET_DASHBOARD_CONSOLE_CREATOR_SETTINGS =
  'SET_DASHBOARD_CONSOLE_CREATOR_SETTINGS';

export const SET_DASHBOARD_SESSION = 'SET_DASHBOARD_SESSION';

export const SET_CONTROLLER_CONFIGURATION = 'SET_CONTROLLER_CONFIGURATION';

export const SET_DRAFT_MANAGER = 'SET_DRAFT_MANAGER';

export const SET_SERVER_CONFIG_VALUES = 'SET_SERVER_CONFIG_VALUES';

export const SET_FILE_STORAGE = 'SET_FILE_STORAGE';

export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';

export const SET_USER = 'SET_USER';

export const SET_WORKSPACE = 'SET_WORKSPACE';

export const SET_WORKSPACE_STORAGE = 'SET_WORKSPACE_STORAGE';
