enum OptionType {
  ADVANCED_SETTINGS = 'ADVANCED_SETTINGS',
  AGGREGATIONS = 'AGGREGATIONS',
  AGGREGATION_EDIT = 'AGGREGATIONS_EDIT',
  CHART_BUILDER = 'CHART_BUILDER',
  CUSTOM_COLUMN_BUILDER = 'CUSTOM_COLUMN_BUILDER',
  QUICK_FILTERS = 'QUICK_FILTERS',
  ROLLUP_ROWS = 'ROLLUP_ROWS',
  SEARCH_BAR = 'SEARCH_BAR',
  SELECT_DISTINCT = 'SELECT_DISTINCT',
  TABLE_EXPORTER = 'TABLE_EXPORTER',
  VISIBILITY_ORDERING_BUILDER = 'VISIBILITY_ORDERING_BUILDER',
}

export default OptionType;
