name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [e2e-github-action]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Get server:latest SHA
        run: |
          docker pull --quiet ghcr.io/deephaven/server:latest
          docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/deephaven/server:latest > container_sha.txt
          echo "container_sha=$(cat container_sha.txt)" >> $GITHUB_ENV
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
