# This workflow will automatically create a PR in deephaven-core to update the WEB_VERSION when a new web version is published
name: Update deephaven-core web version

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Publish Packages']
    types:
      - completed
  # TODO: Remove `pull_request`, just used for debugging right now
  pull_request:
jobs:
  update-core:
    runs-on: ubuntu-22.04
    steps:
      - name: Update deephaven-core
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/mofojed/deephaven-core/actions/workflows/update-web.yml/dispatches --data '{"ref": "main"}'
