# This workflow will automatically create a PR in deephaven-core to update the WEB_VERSION when a new web version is published
name: Update deephaven-core web version

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
jobs:
  update-core:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout latest web-client-ui
        uses: actions/checkout@v3
        with:
          ref: main
          path: web-client-ui
      - name: Checkout latest deephaven-core
        uses: actions/checkout@v3
        with:
          ref: main
          path: deephaven-core
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Get latest web versions
        id: package_versions
        working-directory: ./web-client-ui
        run: |
          # Selecting a random character for EOF https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo npm pkg get version --ws
          echo "VERSIONS<<$EOF" >> $GITHUB_OUTPUT
          npm pkg get version --ws >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: Update deephaven-core
        run: |
          echo "`pwd`"
          echo "${{fromJson(steps.package_versions.outputs.VERSIONS).["@deephaven/code-studio"]}}"
